[tool.poetry]
name = "insa-5if-ot8-tp1-text-classification"
version = "0.1.0"
description = ""
authors = ["Charles S <cfstcyr.git@pm.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
